// currentUser
export const LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY';
export const LOGOUT_SUCCESSFULLY = 'LOGOUT_SUCCESSFULLY';

// uiState
export const SET_UI_STATE_MODE = 'SET_UI_STATE_MODE';
export const TOOGLE_UI_STATE_MODE = 'TOOGLE_UI_STATE_MODE';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const TOGGLE_SIDEBAR_OPEN = 'TOGGLE_SIDEBAR_OPEN';
export const SET_SIDEBAR_OPEN = 'SET_SIDEBAR_OPEN';

// category
export const CREATE_CATEGORY_SUCCESSFULLY = 'CREATE_CATEGORY_SUCCESSFULLY';
export const UPDATE_CATEGORY_SUCCESSFULLY = 'UPDATE_CATEGORY_SUCCESSFULLY';
export const FETCH_CATEGORIES_SUCCESSFULLY = 'FETCH_CATEGORIES_SUCCESSFULLY';
export const CHANGE_SEARCH_VALUE_FOR_CATEGORY =
  'CHANGE_SEARCH_VALUE_FOR_CATEGORY';
export const CHANGING_SORTING_FOR_CATEGORY = 'CHANGING_SORTING_FOR_CATEGORY';
export const SET_SELECTED_CATEGORIES = 'SET_SELECTED_CATEGORIES';
export const SET_SEARCH_CATEGORY = 'SET_SEARCH_CATEGORY';

// task
export const CREATE_TASK_SUCCESSFULLY = 'CREATE_TASK_SUCCESSFULLY';
export const FETCH_TASKS_SUCCESSFULLY = 'FETCH_TASKS_SUCCESSFULLY';
export const CHANGE_SEARCH_VALUE_FOR_TASK = 'CHANGE_SEARCH_VALUE_FOR_TASK';
export const CHANGING_SORTING_FOR_TASK = 'CHANGING_SORTING_FOR_TASK';

// dashboard
export const CHANGE_SEARCH_VALUE_FOR_DASHBOARD =
  'CHANGE_SEARCH_VALUE_FOR_DASHBOARD';
export const CHANGING_SORTING_FOR_DASHBOARD = 'CHANGING_SORTING_FOR_DASHBOARD';

// activity
export const CREATE_ACTIVITY_SUCCESSFULLY = 'CREATE_ACTIVITY_SUCCESSFULLY';
export const FETCH_ACTIVITIES_SUCCESSFULLY = 'FETCH_ACTIVITIES_SUCCESSFULLY';
