// currentUser
export const LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY';
export const LOGOUT_SUCCESSFULLY = 'LOGOUT_SUCCESSFULLY';

// uiState
export const SET_UI_STATE_MODE = 'SET_UI_STATE_MODE';
export const TOOGLE_UI_STATE_MODE = 'TOOGLE_UI_STATE_MODE';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

// category
export const CREATE_CATEGORY_SUCCESSFULLY = 'CREATE_CATEGORY_SUCCESSFULLY';
